version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    container_name: balancing_market_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build:
      context: .
    restart: always
    container_name: balancing_market_api
    environment:
      DATABASE_URL: postgresql+psycopg2://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      SAGEMAKER_ENDPOINT: ${SAGEMAKER_ENDPOINT}
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: ["/app/start.sh"]

volumes:
  pg_data:

