version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    container_name: balancing_market_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U $DB_USER -d $DB_NAME'"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
    restart: always
    container_name: balancing_market_api
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    command: ["/app/start.sh"]

volumes:
  pg_data:
