AWSTemplateFormatVersion: "2010-09-09"
Description: "Application stack for deploying Lambda functions and logging."

Parameters:
  ComputeStackName:
    Type: String
    Description: "Name of the compute stack to import values from"

Resources:
  ScraperFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-scraper"
      Runtime: python3.9
      Handler: eirgrid_scraper.handler
      Code:
        S3Bucket: !ImportValue balancing-market-compute-DataBucketName
        S3Key: "lambda/eirgrid_scraper.zip"
      MemorySize: 256
      Timeout: 300
      Role: !ImportValue balancing-market-compute-LambdaRoleArn
      Environment:
        Variables:
          BUCKET_NAME: !ImportValue balancing-market-compute-DataBucketName

  ScraperSchedule:
    Type: AWS::Events::Rule
    Properties:
      ScheduleExpression: "rate(1 day)"
      Targets:
        - Arn: !GetAtt ScraperFunction.Arn
          Id: "ScraperLambdaTarget"

  ScraperPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ScraperFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt ScraperSchedule.Arn

Outputs:
  ScraperFunctionArn:
    Description: "ARN of the Scraper Lambda function"
    Value: !GetAtt ScraperFunction.Arn
    Export:
      Name: !Sub "${AWS::StackName}-ScraperFunctionArn"

